version: '2'

services:
  postgresql:
    image: sameersbn/postgresql:9.6-2
    environment:
    - DB_USER=admin
    - DB_PASS=admin
    - DB_NAME=main
    ports:
    - "5432:5432"
    volumes:
    - ./postgresql:/var/lib/postgresql
